server:
  port: 8080
office:
  filesizeMax: 5242880
  saveRootPath: F:/OnlyOfficeFile
  storageFolder: app_data
  baseUrl: http://localhost:6831
  docService:
    viewedDocs: .pdf|.djvu|.xps
    editedDocs: .docx|.xlsx|.csv|.pptx|.txt
    convertDocs: .docm|.dotx|.dotm|.dot|.doc|.odt|.fodt|.ott|.xlsm|.xltx|.xltm|.xlt|.xls|.ods|.fods|.ots|.pptm|.ppt|.ppsx|.ppsm|.pps|.potx|.potm|.pot|.odp|.fodp|.otp|.rtf|.mht|.html|.htm|.epub
    timeout: 120000
    secret: ''
    url:
      converter: ${office.baseUrl}/ConvertService.ashx
      tempstorage: ${office.baseUrl}/ResourceService.ashx
      api: ${office.baseUrl}/web-apps/apps/api/documents/api.js
      preloader: ${office.baseUrl}/web-apps/apps/api/documents/cache-scripts.html
      callbackServer: http://192.168.26.1:8080/callback/office  #给onlyoffice提供回调接口，同步保存文件
logging:
  level:
    root: debug
ftp:
  open: true
  host: 192.168.26.1
  port: 21
  username: lingxiao
  password: 12345678
  baseUrl: http://file.lingxiao.com  # 文件地址前缀
  uploadPath: "/temp"
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
oss:
  accessKey: V_ZleIlYzHPjekmAuRvV_MDkk69VZWM12f # 设置好账号的ACCESS_KEY和SECRET_KEY
  secretKey: U8SndxcceqMZGIKPL3gEPkYRNrP75cJlOH
  bucketName: function  # 要上传的UrlAccessDecisionManager空间
  prefixImg: http://img.liniao.top/
  rootPath: /OnlyOffice